version: "3.8"

services:
  nodebb:
    build: .
    container_name: nodebb
    restart: always
    environment:
      - DATABASE=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - NODE_ENV=production
    ports:
      - "4567:4567"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: nodebb-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
